name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build backend
        run: mvn -f backend/pom.xml -B -DskipTests clean package
      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build --if-present